# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/karel/github/ulysses

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/karel/github/ulysses

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/karel/github/ulysses/CMakeFiles /Users/karel/github/ulysses/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/karel/github/ulysses/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ulysses

# Build rule for target.
ulysses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ulysses
.PHONY : ulysses

# fast build rule for target.
ulysses/fast:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/build
.PHONY : ulysses/fast

bloom.o: bloom.cpp.o
.PHONY : bloom.o

# target to build an object file
bloom.cpp.o:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/bloom.cpp.o
.PHONY : bloom.cpp.o

bloom.i: bloom.cpp.i
.PHONY : bloom.i

# target to preprocess a source file
bloom.cpp.i:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/bloom.cpp.i
.PHONY : bloom.cpp.i

bloom.s: bloom.cpp.s
.PHONY : bloom.s

# target to generate assembly for a file
bloom.cpp.s:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/bloom.cpp.s
.PHONY : bloom.cpp.s

kmer.o: kmer.cpp.o
.PHONY : kmer.o

# target to build an object file
kmer.cpp.o:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/kmer.cpp.o
.PHONY : kmer.cpp.o

kmer.i: kmer.cpp.i
.PHONY : kmer.i

# target to preprocess a source file
kmer.cpp.i:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/kmer.cpp.i
.PHONY : kmer.cpp.i

kmer.s: kmer.cpp.s
.PHONY : kmer.s

# target to generate assembly for a file
kmer.cpp.s:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/kmer.cpp.s
.PHONY : kmer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/main.cpp.s
.PHONY : main.cpp.s

seed.o: seed.cpp.o
.PHONY : seed.o

# target to build an object file
seed.cpp.o:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/seed.cpp.o
.PHONY : seed.cpp.o

seed.i: seed.cpp.i
.PHONY : seed.i

# target to preprocess a source file
seed.cpp.i:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/seed.cpp.i
.PHONY : seed.cpp.i

seed.s: seed.cpp.s
.PHONY : seed.s

# target to generate assembly for a file
seed.cpp.s:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/seed.cpp.s
.PHONY : seed.cpp.s

utils/MurmurHash3.o: utils/MurmurHash3.cpp.o
.PHONY : utils/MurmurHash3.o

# target to build an object file
utils/MurmurHash3.cpp.o:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/utils/MurmurHash3.cpp.o
.PHONY : utils/MurmurHash3.cpp.o

utils/MurmurHash3.i: utils/MurmurHash3.cpp.i
.PHONY : utils/MurmurHash3.i

# target to preprocess a source file
utils/MurmurHash3.cpp.i:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/utils/MurmurHash3.cpp.i
.PHONY : utils/MurmurHash3.cpp.i

utils/MurmurHash3.s: utils/MurmurHash3.cpp.s
.PHONY : utils/MurmurHash3.s

# target to generate assembly for a file
utils/MurmurHash3.cpp.s:
	$(MAKE) -f CMakeFiles/ulysses.dir/build.make CMakeFiles/ulysses.dir/utils/MurmurHash3.cpp.s
.PHONY : utils/MurmurHash3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ulysses"
	@echo "... bloom.o"
	@echo "... bloom.i"
	@echo "... bloom.s"
	@echo "... kmer.o"
	@echo "... kmer.i"
	@echo "... kmer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... seed.o"
	@echo "... seed.i"
	@echo "... seed.s"
	@echo "... utils/MurmurHash3.o"
	@echo "... utils/MurmurHash3.i"
	@echo "... utils/MurmurHash3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

